CREATE SCHEMA issue_management;

USE issue_management;

CREATE TABLE users (
    id INTEGER AUTO_INCREMENT NOT NULL ,
    name VARCHAR(255),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE  CURRENT_TIMESTAMP,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE issues(
    id INTEGER AUTO_INCREMENT NOT NULL ,
    issue VARCHAR(255),
    description MEDIUMTEXT,
    status enum('CREATE', 'ASSIGNED','PROGRESS', 'REVIEW', 'COMPLETED') DEFAULT 'CREATE',
    fixed boolean DEFAULT FALSE,
    user_id INTEGER NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE  CURRENT_TIMESTAMP,
    CONSTRAINT issues_pk PRIMARY KEY (id),
    CONSTRAINT issues_user_fk FOREIGN KEY (user_id) REFERENCES users(id)
);